version: "3.9"

services:
  ichgram:
    build:
      context: ./BE
      dockerfile: dockerfile
    container_name: ichgram
    ports:
      - "5001:5001"
      - "5005:5005"
      #добавить при запуске env
    # env_file:
    #   - .env
    # depends_on:
    #   - mongo
    # volumes:
    #   - .env:/app/.env

  frontichgram:
    build:
      context: ./FE
      dockerfile: dockerfile
    container_name: frontichgram
    ports:
      - "5173:5173"
    

#   mongo-database:
#     container_name: mongo-database
#     image: mongo:7
#     restart: always
#     ports:
#       - 27017:27017
#     command: --auth --bind_ip 0.0.0.0
#     environment:
#        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
#        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
#        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
#     env_file:
#       - .env
#     volumes:
#       - ./data/db:/data/db

# volumes:
#   mongo-data: